### ISSUE TITLE
YAML parsing

### ISSUE THREAD

**Issue by deven96** [bisohns/saido#7]
Create utility or package for parsing yaml files and getting the appropriate arguments to retrieve host metrics

**Comment by deven96** [comment]
```yaml
title: x
hosts:
    - type: [ssh, local-unix, local-windows, web]
      name: x
      auth:
          hosts: [ ] /file
          priv_key:
          priv_key_pass:
      metrics:
          - name: df
            chart: pie
          - meminfo
          - tasklist
 ```
